# Generated by Django 5.0.2 on 2024-02-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='agent',
        ),
        migrations.AddField(
            model_name='estate',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], default='sale', max_length=10),
            preserve_default=False,
        ),
    ]
