# Generated by Django 5.0.2 on 2024-03-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0005_alter_estate_listing_type_savedsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='garage',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='garden',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='maxPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='max_bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='max_bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='minPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='min_bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='min_bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
